server:
  port: 8060

spring:
  application:
    name: end-user-service

  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:msa-test;  #접속 URL
    username: sa
    password:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/